const express = require('express');
const path = require('path');
require('dotenv').config();
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const cors = require('cors');
const app = express();
app.use(helmet({ contentSecurityPolicy:false }));
app.use(cors({ origin: process.env.CORS_ORIGIN || true }));
app.use(express.json({ limit:'1mb' }));
app.use(rateLimit({ windowMs:15*60*1000, max:300 }));
app.get('/health', (req,res)=>res.json({ok:true, service:'dilabit-node-pos'}));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/products', require('./routes/products'));
app.use('/api/stock', require('./routes/stock'));
app.use('/api/sales', require('./routes/sales'));
app.use('/api/reports', require('./routes/reports'));
app.use('/api/sync', require('./routes/sync'));
app.use('/api/payments', require('./routes/payments'));
app.use('/api/backups', require('./routes/backups'));
app.use('/api/controlled-drugs', require('./routes/controlled-drugs'));
app.use('/api/audit', require('./routes/audit'));
app.use(express.static(path.join(__dirname,'client')));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'client','index.html')));
app.use((err,req,res,next)=>{ console.error(err); res.status(500).json({error: process.env.NODE_ENV==='production'?'Internal server error':err.message}); });
app.listen(process.env.PORT || 3000, ()=>console.log(`Node POS listening on ${process.env.PORT || 3000}`));
